apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: {{ template "tf-job.fullname" . }}
  labels:
    app: {{ template "tf-job.name" . }}
    chart: {{ template "tf-job.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              name: tensorflow
          restartPolicy: OnFailure
