apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorflow-notebook.fullname" . }}
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6006
      targetPort: tensorboard
      protocol: TCP
      name: tensorboard
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.tensorboardPort.http)))}}
      nodePort: {{ .Values.tensorboardPort.http }}
      {{- end }}
    - port: 8888
      targetPort: jupyter
      protocol: TCP
      name: jupyter
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.notebookPort.http)))}}
      nodePort: {{ .Values.notebookPort.http }}
      {{- end }}
  selector:
    app: {{ template "tensorflow-notebook.name" . }}
    release: {{ .Release.Name }}
