# Default values for ack-tensorflow-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jupyter:
  image:
    repository: tensorflow/tensorflow
    tag: 1.7.1-devel-gpu-py3
    pullPolicy: IfNotPresent
  password: tensorflow
  resources:
    limits: 
      nvidia.com/gpu: 1
tensorboard:
  image:
    repository: tensorflow/tensorflow
    tag: 1.7.1-devel-gpu-py3
    pullPolicy: IfNotPresent
notebookPort:
  http: ""
tensorboardPort:
  http: ""
service:
  type: LoadBalancer
