name: tensorflow-serving
home: https://github.com/kubernetes/charts
version: 0.0.1
appVersion: 0.0.1
description: TensorFlow Serving is an open-source software library for serving machine learning models.
sources:
- https://github.com/tensorflow/serving
maintainers:
- name: david
  email: david@david.com
