# Default values for ack-tensorflow-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jupyter:
  image:
    repository: tensorflow/tensorflow
    tag: 1.7.1-devel-gpu-py3
    pullPolicy: IfNotPresent
  password: tensorflow
  gpuNumber: 1
tensorboard:
  image:
    repository: tensorflow/tensorflow
    tag: 1.7.1-devel-py3
    pullPolicy: IfNotPresent
notebookPort:
  http: ""
tensorboardPort:
  http: ""
service:
  type: NodePort
persistent:
  enable: false
  size: 50Gi
  pvc: "david-pvc"
  path: "/data"