name: Tensorflow-notebook  # Name of the Catalog Entry
description: | # Description of the Catalog Entry
  Deep Learning Framework
version: Tensorflow 0.1 (GPU)  # Version of the Catalog to be used
category: Deep Learning # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
